global_parameters:
  - window_length: 4
  - curriculum_learning: False
  - no_ins: 4
  - difficulty: 500

model_parameters:
  - activation_function: "relu"
  - data_format: "channels_first"
  - conv2d:
      - layer_1_kernel_size: 32
      - layer_2_kernel_size: 32
      - layer_3_kernel_size: 32
  - dense:
      - layer_1_neurons: 128
      - layer_2_neurons: 128
      - layer_3_neurons: 128
      - layer_4_neurons: 128
      - layer_5_neurons: 128
  - compile:
      - optimizer_lr: 0.0001
      - metrics: "mae"
  - fit:
      - nb_steps: 5_020_000
      - visualize: False
      - verbose: 2

DQNAgent_parameters:
  - policy:
      - attr: "eps"
      - value_max: 1.0
      - value_min: 0.1
      - value_test: 0.05
      - nb_steps: 300_000
  - memory:
      - limit: 150_000
  - DQNAgent_function:
      - target_model_update: 0.01
      - enable_double_dqn: True
      - enable_dueling_network: True
      - dueling_type: "avg"
      - nb_steps_warmup: 20_000
