global_parameters:
  - window_length: 4

model_parameters:
  - activation_function: "relu"
  - data_format: "channels_first"
  - conv2d:
      - layer_1_kernel_size: 32
      - layer_2_kernel_size: 64
      - layer_3_kernel_size: 64
  - dense:
      - layer_1_neurons: 512
      - layer_2_neurons: 256
  - compile:
      - optimizer_lr: 0.0001
      - metrics: "mae"
  - fit:
      - nb_steps: 1_000_000
      - visualize: False
      - verbose: 2

DQNAgent_parameters:
  - policy:
      - attr: "eps"
      - value_max: 1.0
      - value_min: 0.1
      - value_test: 0.05
      - nb_steps: 500_000
  - memory:
      - limit: 500_000
  - DQNAgent_function:
      - target_model_update: 0.01
      - enable_double_dqn: True
      - enable_dueling_network: True
      - dueling_type: "avg"
      - nb_steps_warmup: 15_000
